### ISSUE TITLE
Unicode character issue.

### ISSUE THREAD

**Issue by JohnRSim** [FortAwesome/vue-fontawesome#145]
Text is being replaced as unicode characters?
Expected to just see Robot Icon with the wording Print next to it - however print is converted to an icon..

```html
<select>
<option>
   &#xf544; Print
</option>
</select>
```

```css
select, option {
    font-family: 'Font Awesome 5 Free', Arial;
    display: inline-block;
    font-style: normal;
    font-variant: normal;
    text-rendering: auto;
    line-height: 1;
    font-weight: 900;
}
```
![image](https://user-images.githubusercontent.com/364208/47227246-459b8d00-d3ba-11e8-91b2-d57e1db2350e.png)
