### ISSUE TITLE
Postcss8 loader error on svg core styles.css

### ISSUE THREAD

**Issue by K-zimm** [FortAwesome/vue-fontawesome#341]
Running in nuxt with postcss8.

It is having trouble with one particular line. When I commend it out build completes fine and app works great. Seems that it doesn't like the calc() function on line 202 of styles.css in fontawesome-svg-core The parser cries about the -1.

![image](https://user-images.githubusercontent.com/22413842/149820684-42d9de1e-0e5e-483c-b379-5930caf6e045.png)

**Comment by robmadole** [comment]
@K-zimm can you provide a reproducible test case for this?

**Comment by tobiasdiez** [comment]
I got the same issue while upgrading fontawesome-svg-core from 1.2.36 to 1.3.0 https://github.com/JabRef/JabRefOnline/pull/837. 
As @K-zimm says, the problem is in the line for `left`:
```css
.fa-li {
  left: calc(var(--fa-li-width, 2em) * -1);
  position: absolute;
  text-align: center;
  width: var(--fa-li-width, 2em);
  line-height: inherit; }
```
